"""Appendix H tables for the Pavia University replication: the readiness-scan table from
results/exp3_paviau/readiness_scan.csv, then the generated Exp 3 (EXP3_DATASET=paviau ->
appendix_exp3_paviau_tables.tex) and Exp 4 (appendix_exp4_paviau_tables.tex) tables by \\input.
Run make_tables_exp3.py (with EXP3_DATASET=paviau) and make_tables_exp4.py first."""
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "paper" / "sections_iclr_v2" / "appendix_pavia_tables.tex"
L = []
scan = pd.read_csv(ROOT / "results" / "exp3_paviau" / "readiness_scan.csv")
L.append("\\begin{table}[htbp]\\centering\\scriptsize")
L.append("\\caption{Pavia University readiness scan (tile-disjoint halves of the training split): centre-only "
         "discriminant (oracle) and the discriminant on a random $K$-dimensional linear encoder's output "
         "(mean [min, max] over three encoders), standardized and PCA-whitened inputs; $|\\cos|$ is the cosine "
         "between the class-mean contrast and the first principal direction.}\\label{tab:pavia_scan}")
L.append("\\begin{tabular}{llcccccc}\\toprule")
L.append("pair & preprocessing & oracle & $K=2$ & $K=4$ & $K=12$ & $K=32$ & $|\\cos|$ \\\\ \\midrule")
for pair, g in scan.groupby("pair", sort=False):
    for prep, h in g.groupby("prep", sort=False):
        cells = []
        for Kb in (2, 4, 12, 32):
            r = h[h["K"] == Kb].iloc[0]
            cells.append(f"{r['random_probe_mean']:.3f} [{r['random_probe_min']:.2f}, {r['random_probe_max']:.2f}]")
        L.append(f"{pair.replace('-vs-', ' vs ')} & {prep} & {h['oracle'].iloc[0]:.3f} & " + " & ".join(cells) +
                 f" & {h['cos_contrast_v1'].iloc[0]:.2f} \\\\")
L.append("\\bottomrule\\end{tabular}\\end{table}")
for f in ("appendix_exp3_paviau_tables", "appendix_exp4_paviau_tables"):
    L.append(f"\\IfFileExists{{sections_iclr_v2/{f}.tex}}{{\\input{{sections_iclr_v2/{f}}}}}{{}}")
OUT.write_text("% generated by paper/figures_src/make_tables_pavia.py\n" + "\n".join(L) + "\n")
print(f"wrote {OUT}")
